/**
 * CUSTOM ACTIONS
 */
export const RECORD_FETCH_REQUEST = "RECORD_FETCH_REQUEST";
export const RECORD_FETCH_SUCCESS = "RECORD_FETCH_SUCCESS";
export const RECORD_FETCH_FAILURE = "RECORD_FETCH_FAILURE";

export const CHOICES_FETCH_REQUEST = "CHOICES_FETCH_REQUEST";
export const CHOICES_FETCH_SUCCESS = "CHOICES_FETCH_SUCCESS";
export const CHOICES_FETCH_FAILURE = "CHOICES_FETCH_FAILURE";

export const DATA_REQUEST_START = "DATA_REQUEST_START";
export const DATA_REQUEST_PROGRESS = "DATA_REQUEST_PROGRESS";


/**
 * CONSTANTS
 */
 export const MODE_STATIC = "STATIC";
 export const MODE_RECORD = "RECORD";

 export const CURRENT_STAGE_CHANGED = "CURRENT_STAGE_CHANGED";
