/**
 * CUSTOM ACTIONS
 */


export const STAGE_CHOICES_REQUEST = "STAGE_CHOICES_REQUEST";
export const STAGE_CHOICES_SUCCESS = "STAGE_CHOICES_SUCCESS";
export const STAGE_CHOICES_FAILURE = "STAGE_CHOICES_FAILURE";

export const CURRENT_STAGE_REQUEST = "CURRENT_STAGE_REQUEST";
export const CURRENT_STAGE_SUCCESS = "CURRENT_STAGE_SUCCESS";
export const CURRENT_STAGE_FAILURE = "CURRENT_STAGE_FAILURE";

export const DATA_FETCH_START    = "DATA_FETCH_START";
export const DATA_FETCH_PROGRESS = "DATA_FETCH_PROGRESS";


/**
 * CONSTANTS
 */
 export const MODE_STATIC = "STATIC";
 export const MODE_RECORD = "RECORD";

 export const CURRENT_STAGE_CHANGED = "CURRENT_STAGE_CHANGED";
